### ISSUE TITLE
String pad length doesn't follow the RFC spec

### ISSUE THREAD

**Issue by fdawg4l** [davecheney/nfs#1]
It looks like the pad for strings is being computed incorrectly.  The length is aligned to 4 bytes and the `mod` operator isn't doing that.

**Comment by davecheney** [comment]
I'm sorry this code is dead. You're welcome to fork it and maintain your
own copy

**Comment by fdawg4l** [comment]
Sounds good.  Will do.  Thanks!  Do you have a license preference?

**Comment by davecheney** [comment]
None whatsover.

I hereby donate this code to the public domain.
